import { FrameTheme, ThemeId } from '@/types';

export const FRAME_THEMES: Record<ThemeId, FrameTheme> = {
  'hhgoa-vibrant': {
    id: 'hhgoa-vibrant',
    name: 'HH Goa Tri-Color',
    description: 'Official HH Goa vibrant aesthetic with Neon Green, Electric Yellow & Cyber Pink',
    primaryColor: '#00FF66',
    accentColor: '#FFE600',
    badgeBg: 'linear-gradient(135deg, #00FF66 0%, #FFE600 50%, #FF007A 100%)',
    cardBg: '#050505',
    textColor: '#FFFFFF',
    subtextColor: '#FFE600',
    borderStyle: 'border-[#00FF66]/50',
  },
  'neon-green': {
    id: 'neon-green',
    name: 'Neon Green',
    description: 'Terminal hacker vibrant green (#00FF66) with electric yellow accents',
    primaryColor: '#00FF66',
    accentColor: '#FFE600',
    badgeBg: 'linear-gradient(135deg, #00FF66 0%, #10B981 100%)',
    cardBg: '#030804',
    textColor: '#FFFFFF',
    subtextColor: '#00FF66',
    borderStyle: 'border-[#00FF66]/40',
  },
  'cyber-pink': {
    id: 'cyber-pink',
    name: 'Cyber Pink',
    description: 'Hot pink (#FF007A) aesthetic with bright neon yellow highlights',
    primaryColor: '#FF007A',
    accentColor: '#FFE600',
    badgeBg: 'linear-gradient(135deg, #FF007A 0%, #EC4899 100%)',
    cardBg: '#0D0207',
    textColor: '#FFFFFF',
    subtextColor: '#FF007A',
    borderStyle: 'border-[#FF007A]/40',
  },
  'electric-yellow': {
    id: 'electric-yellow',
    name: 'Electric Yellow',
    description: 'Vibrant neon yellow (#FFE600) with hot pink highlights',
    primaryColor: '#FFE600',
    accentColor: '#FF007A',
    badgeBg: 'linear-gradient(135deg, #FFE600 0%, #F59E0B 100%)',
    cardBg: '#0A0901',
    textColor: '#FFFFFF',
    subtextColor: '#FFE600',
    borderStyle: 'border-[#FFE600]/40',
  },
  'goa-sunset': {
    id: 'goa-sunset',
    name: 'Sunset Flame',
    description: 'Vibrant tropical sunset orange and warm golden accents',
    primaryColor: '#FF5500',
    accentColor: '#FFB800',
    badgeBg: 'linear-gradient(135deg, #FF5500 0%, #FF8C00 100%)',
    cardBg: '#0F172A',
    textColor: '#FFFFFF',
    subtextColor: '#94A3B8',
    borderStyle: 'border-orange-500/30',
  },
  'deep-navy': {
    id: 'deep-navy',
    name: 'Deep Navy',
    description: 'Sleek minimalist conference styling with silver typography',
    primaryColor: '#38BDF8',
    accentColor: '#818CF8',
    badgeBg: 'linear-gradient(135deg, #0F172A 0%, #1E293B 100%)',
    cardBg: '#0B0F19',
    textColor: '#F8FAFC',
    subtextColor: '#64748B',
    borderStyle: 'border-slate-700/50',
  },
  'cyber-neon': {
    id: 'cyber-neon',
    name: 'Cyber Violet',
    description: 'High-tech developer neon glow with electric indigo highlights',
    primaryColor: '#8B5CF6',
    accentColor: '#EC4899',
    badgeBg: 'linear-gradient(135deg, #6366F1 0%, #A855F7 100%)',
    cardBg: '#090514',
    textColor: '#F3E8FF',
    subtextColor: '#A78BFA',
    borderStyle: 'border-purple-500/30',
  },
  'vip-gold': {
    id: 'vip-gold',
    name: 'VIP Gold',
    description: 'Exclusive pass trim with gold foil and polished finish',
    primaryColor: '#F59E0B',
    accentColor: '#FCD34D',
    badgeBg: 'linear-gradient(135deg, #D97706 0%, #F59E0B 100%)',
    cardBg: '#18130B',
    textColor: '#FFFBEB',
    subtextColor: '#FCD34D',
    borderStyle: 'border-amber-500/40',
  },
};

export const DEFAULT_BUILDER_INFO = {
  name: 'Alex Rivera',
  role: 'Full Stack Engineer',
  company: 'NextGen AI Lab',
  college: 'IIT Goa',
  location: 'Goa, India',
  builderTitle: 'The AI Architect',
  customHashtag: '#FrameInGoa',
};

export const SUGGESTED_TITLES = [
  'The AI Architect',
  'Frontend Wizard',
  'Cloud Explorer',
  'Shipping Machine',
  'Prompt Engineer',
  'Bug Hunter',
  'Pixel Crafter',
  'Backend Alchemist',
  'React Ninja',
  'Data Explorer',
  'Rust Magician',
  'Full Stack Overlord',
  'Agentic Systems Pioneer',
  'Goa Hackathon Voyager',
  'GPU Whisperer',
  'Distributed Systems Guru',
  'LLM Engineer',
  'Zero-Bug Zealot',
];

export const MAX_FILE_SIZE = 15 * 1024 * 1024; // 15MB
export const ACCEPTED_IMAGE_TYPES = [
  'image/jpeg',
  'image/jpg',
  'image/png',
  'image/webp',
  'image/heic',
  'image/heif',
];
