import { FrameTheme, ThemeId } from '@/types';

export const FRAME_THEMES: Record<ThemeId, FrameTheme> = {
  'hhgoa-editorial': {
    id: 'hhgoa-editorial',
    name: 'HH Goa Editorial',
    description: 'Official HH Goa design palette: Forest Green, Cream, Sun Yellow & Hot Pink',
    primaryColor: '#FFD400',
    accentColor: '#FF007A',
    badgeBg: 'linear-gradient(135deg, #FFD400 0%, #FF007A 100%)',
    cardBg: '#F7F1DF',
    textColor: '#0A4C2B',
    subtextColor: '#0E6B3A',
    borderStyle: 'border-[#1E5A3B]',
  },
  'goa-festival': {
    id: 'goa-festival',
    name: 'Festival Yellow',
    description: 'Electric sun yellow backdrop with hot pink and forest green accents',
    primaryColor: '#FF007A',
    accentColor: '#0E6B3A',
    badgeBg: 'linear-gradient(135deg, #FF007A 0%, #FFD400 100%)',
    cardBg: '#FFD400',
    textColor: '#0A4C2B',
    subtextColor: '#FF007A',
    borderStyle: 'border-[#0A4C2B]',
  },
  'palm-green': {
    id: 'palm-green',
    name: 'Palm Forest',
    description: 'Deep Goa forest green backdrop with yellow foil credentials',
    primaryColor: '#FFD400',
    accentColor: '#F7F1DF',
    badgeBg: 'linear-gradient(135deg, #0E6B3A 0%, #1E5A3B 100%)',
    cardBg: '#0E6B3A',
    textColor: '#F7F1DF',
    subtextColor: '#FFD400',
    borderStyle: 'border-[#FFD400]',
  },
  'cyber-pink': {
    id: 'cyber-pink',
    name: 'Hot Pink Badge',
    description: 'Vibrant hot pink background with cream and yellow typography',
    primaryColor: '#FFD400',
    accentColor: '#F7F1DF',
    badgeBg: 'linear-gradient(135deg, #FF007A 0%, #E0006C 100%)',
    cardBg: '#FF007A',
    textColor: '#FFFFFF',
    subtextColor: '#FFD400',
    borderStyle: 'border-[#0A4C2B]',
  },
  'goa-sunset': {
    id: 'goa-sunset',
    name: 'Sunset Orange',
    description: 'Vibrant tropical sunset orange and warm golden accents',
    primaryColor: '#FF5500',
    accentColor: '#FFB800',
    badgeBg: 'linear-gradient(135deg, #FF5500 0%, #FF8C00 100%)',
    cardBg: '#F7F1DF',
    textColor: '#0A4C2B',
    subtextColor: '#0E6B3A',
    borderStyle: 'border-[#1E5A3B]',
  },
  'deep-navy': {
    id: 'deep-navy',
    name: 'Deep Navy',
    description: 'Sleek minimalist conference styling with silver typography',
    primaryColor: '#38BDF8',
    accentColor: '#818CF8',
    badgeBg: 'linear-gradient(135deg, #0F172A 0%, #1E293B 100%)',
    cardBg: '#F7F1DF',
    textColor: '#0A4C2B',
    subtextColor: '#0E6B3A',
    borderStyle: 'border-slate-700/50',
  },
  'cyber-neon': {
    id: 'cyber-neon',
    name: 'Cyber Violet',
    description: 'High-tech developer neon glow with electric indigo highlights',
    primaryColor: '#8B5CF6',
    accentColor: '#EC4899',
    badgeBg: 'linear-gradient(135deg, #6366F1 0%, #A855F7 100%)',
    cardBg: '#F7F1DF',
    textColor: '#0A4C2B',
    subtextColor: '#0E6B3A',
    borderStyle: 'border-purple-500/30',
  },
  'vip-gold': {
    id: 'vip-gold',
    name: 'VIP Gold',
    description: 'Exclusive pass trim with gold foil and polished finish',
    primaryColor: '#F59E0B',
    accentColor: '#FCD34D',
    badgeBg: 'linear-gradient(135deg, #D97706 0%, #F59E0B 100%)',
    cardBg: '#F7F1DF',
    textColor: '#0A4C2B',
    subtextColor: '#D97706',
    borderStyle: 'border-amber-500/40',
  },
};

export const DEFAULT_BUILDER_INFO = {
  name: 'Alex Rivera',
  role: 'Full Stack Engineer',
  company: '2:47 PM Studio',
  college: 'IIT Goa',
  location: 'Goa, India',
  builderTitle: 'The AI Architect',
  customHashtag: '#FrameInGoa',
};

export const SUGGESTED_TITLES = [
  'The AI Architect',
  'Frontend Wizard',
  'Cloud Explorer',
  'Shipping Machine',
  'Prompt Engineer',
  'Bug Hunter',
  'Pixel Crafter',
  'Backend Alchemist',
  'React Ninja',
  'Data Explorer',
  'Rust Magician',
  'Full Stack Overlord',
  'Agentic Systems Pioneer',
  'Goa Hackathon Voyager',
  'GPU Whisperer',
  'Distributed Systems Guru',
  'LLM Engineer',
  'Zero-Bug Zealot',
];

export const MAX_FILE_SIZE = 15 * 1024 * 1024; // 15MB
export const ACCEPTED_IMAGE_TYPES = [
  'image/jpeg',
  'image/jpg',
  'image/png',
  'image/webp',
  'image/heic',
  'image/heif',
];
