'use client';

/* eslint-disable @next/next/no-img-element */
import React, { useEffect, useState } from 'react';
import { GalleryItem } from '@/app/api/gallery/route';
import { RefreshCw, ExternalLink, Sparkles, CreditCard, Image as ImageIcon, Share2 } from 'lucide-react';
import Link from 'next/link';

export function Gallery() {
  const [items, setItems] = useState<GalleryItem[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [activeFilter, setActiveFilter] = useState<'all' | 'card' | 'frame'>('all');

  const fetchGallery = async () => {
    setIsLoading(true);
    try {
      const res = await fetch('/api/gallery', { cache: 'no-store' });
      if (res.ok) {
        const data = await res.json();
        if (data.success && Array.isArray(data.items)) {
          setItems(data.items);
        }
      }
    } catch (err) {
      console.warn('Failed to load gallery items:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const [supabaseStatus, setSupabaseStatus] = useState<{ connected: boolean; hasUrl: boolean; hasServiceRoleKey: boolean; error?: string } | null>(null);

  const checkSupabaseStatus = async () => {
    try {
      const res = await fetch('/api/supabase-status');
      if (res.ok) {
        const data = await res.json();
        setSupabaseStatus(data);
      }
    } catch {
      // Ignore status fetch fail
    }
  };

  useEffect(() => {
    fetchGallery();
    checkSupabaseStatus();

    const handleNewGraphic = () => {
      fetchGallery();
    };

    if (typeof window !== 'undefined') {
      window.addEventListener('graphicGenerated', handleNewGraphic);
    }

    return () => {
      if (typeof window !== 'undefined') {
        window.removeEventListener('graphicGenerated', handleNewGraphic);
      }
    };
  }, []);

  const filteredItems = items.filter((item) => {
    if (activeFilter === 'card') return item.type === 'card';
    if (activeFilter === 'frame') return item.type === 'frame';
    return true;
  });

  return (
    <section id="gallery" className="py-20 sm:py-28 bg-[#0E6B3A] border-b-2 border-[#1E5A3B] relative font-editorial-mono">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center max-w-2xl mx-auto mb-12">
          <div className="inline-flex items-center gap-2 text-xs font-bold text-[#FFD400] uppercase tracking-widest px-3.5 py-1.5 rounded-full bg-[#FFD400]/20 border border-[#FFD400]/40 shadow-[2px_2px_0px_#0A4C2B]">
            <Sparkles className="w-3.5 h-3.5 text-[#FF007A]" /> LIVE COMMUNITY GALLERY
          </div>
          <h2 className="font-editorial-serif font-bold text-4xl sm:text-6xl text-[#F7F1DF] tracking-tight mt-4 uppercase">
            Builder Showcase
          </h2>
          <p className="text-sm sm:text-base text-[#F7F1DF]/90 mt-2 font-normal">
            Real Builder Passes &amp; Profile Frames generated by the community, hosted on Supabase.
          </p>
        </div>

        {/* Supabase Connection Environment Notice if credentials are not configured on Netlify */}
        {supabaseStatus && !supabaseStatus.connected && (
          <div className="max-w-3xl mx-auto mb-8 bg-[#FFD400] text-[#0A4C2B] border-2 border-[#0A4C2B] rounded-2xl p-4 text-xs shadow-[4px_4px_0px_#0A4C2B]">
            <p className="font-bold uppercase mb-1 text-[#FF007A] flex items-center gap-1.5">
              ⚠️ Supabase Storage Connection Notice
            </p>
            <p>
              To save generated passes globally in Supabase Storage for all users, please set{' '}
              <code className="bg-white/70 px-1.5 py-0.5 rounded border border-[#0A4C2B]">NEXT_PUBLIC_SUPABASE_URL</code> and{' '}
              <code className="bg-white/70 px-1.5 py-0.5 rounded border border-[#0A4C2B]">SUPABASE_SERVICE_ROLE_KEY</code> (or{' '}
              <code className="bg-white/70 px-1.5 py-0.5 rounded border border-[#0A4C2B]">NEXT_PUBLIC_SUPABASE_ANON_KEY</code>) in your Netlify / deployment environment settings.
            </p>
          </div>
        )}

        {/* Filter Controls & Refresh */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 mb-10 max-w-5xl mx-auto">
          <div className="flex items-center gap-2 p-1.5 rounded-full bg-[#F7F1DF] border-2 border-[#0A4C2B] shadow-[3px_3px_0px_#0A4C2B]">
            <button
              onClick={() => setActiveFilter('all')}
              className={`px-4 py-1.5 rounded-full text-xs font-bold font-editorial-display transition-all cursor-pointer ${
                activeFilter === 'all'
                  ? 'bg-[#FF007A] text-white shadow-[2px_2px_0px_#0A4C2B]'
                  : 'text-[#0A4C2B] hover:text-[#FF007A]'
              }`}
            >
              All ({items.length})
            </button>
            <button
              onClick={() => setActiveFilter('card')}
              className={`flex items-center gap-1.5 px-4 py-1.5 rounded-full text-xs font-bold font-editorial-display transition-all cursor-pointer ${
                activeFilter === 'card'
                  ? 'bg-[#FF007A] text-white shadow-[2px_2px_0px_#0A4C2B]'
                  : 'text-[#0A4C2B] hover:text-[#FF007A]'
              }`}
            >
              <CreditCard className="w-3.5 h-3.5" /> Passes ({items.filter((i) => i.type === 'card').length})
            </button>
            <button
              onClick={() => setActiveFilter('frame')}
              className={`flex items-center gap-1.5 px-4 py-1.5 rounded-full text-xs font-bold font-editorial-display transition-all cursor-pointer ${
                activeFilter === 'frame'
                  ? 'bg-[#FF007A] text-white shadow-[2px_2px_0px_#0A4C2B]'
                  : 'text-[#0A4C2B] hover:text-[#FF007A]'
              }`}
            >
              <ImageIcon className="w-3.5 h-3.5" /> Frames ({items.filter((i) => i.type === 'frame').length})
            </button>
          </div>

          <button
            onClick={fetchGallery}
            disabled={isLoading}
            className="flex items-center gap-2 px-4 py-2 rounded-full bg-[#FFD400] text-[#0A4C2B] font-editorial-display font-bold text-xs border-2 border-[#0A4C2B] shadow-[3px_3px_0px_#0A4C2B] hover:translate-x-0.5 transition-all cursor-pointer uppercase"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isLoading ? 'animate-spin' : ''}`} /> Refresh Gallery
          </button>
        </div>

        {/* Gallery Grid */}
        {isLoading ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 max-w-6xl mx-auto">
            {[1, 2, 3].map((n) => (
              <div
                key={n}
                className="aspect-square rounded-3xl bg-[#0E6B3A] border-2 border-[#1E5A3B] animate-pulse flex items-center justify-center p-6"
              >
                <div className="text-center space-y-2">
                  <div className="w-12 h-12 rounded-full bg-[#FFD400]/20 mx-auto" />
                  <p className="text-xs text-[#FFD400]">Loading Supabase graphics...</p>
                </div>
              </div>
            ))}
          </div>
        ) : filteredItems.length > 0 ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 max-w-6xl mx-auto">
            {filteredItems.map((item) => (
              <div
                key={item.id}
                className="group relative rounded-3xl bg-[#F7F1DF] border-2 border-[#0A4C2B] shadow-[6px_6px_0px_#0A4C2B] overflow-hidden flex flex-col justify-between hover:-translate-y-1 transition-all"
              >
                {/* Image Container */}
                <div className="relative aspect-square w-full bg-[#0E6B3A] overflow-hidden border-b-2 border-[#0A4C2B]">
                  <img
                    src={item.imageUrl}
                    alt={`${item.type === 'card' ? 'Builder Pass' : 'Profile Frame'} ${item.id}`}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                    loading="lazy"
                  />

                  {/* Badge */}
                  <div className="absolute top-3 left-3 px-3 py-1 rounded-full bg-[#FF007A] text-white text-[10px] font-bold uppercase tracking-widest border border-[#0A4C2B] shadow-[2px_2px_0px_#0A4C2B] flex items-center gap-1">
                    {item.type === 'card' ? (
                      <>
                        <CreditCard className="w-3 h-3 text-[#FFD400]" /> Builder Pass
                      </>
                    ) : (
                      <>
                        <ImageIcon className="w-3 h-3 text-[#FFD400]" /> Profile Frame
                      </>
                    )}
                  </div>
                </div>

                {/* Footer Controls */}
                <div className="p-4 flex items-center justify-between text-xs font-editorial-mono bg-[#F7F1DF]">
                  <div>
                    <span className="text-[11px] font-bold text-[#0A4C2B] block uppercase truncate max-w-[160px]">
                      {item.builderName || `ID: ${item.id.slice(0, 8)}`}
                    </span>
                    <span className="text-[9px] text-[#0E6B3A] font-bold">#FrameInGoa</span>
                  </div>

                  <div className="flex items-center gap-2">
                    <Link
                      href={item.shareUrl}
                      className="px-3 py-1.5 rounded-xl bg-[#FFD400] text-[#0A4C2B] font-bold text-[10px] border border-[#0A4C2B] shadow-[2px_2px_0px_#0A4C2B] hover:bg-[#FF007A] hover:text-white transition-all flex items-center gap-1 uppercase"
                    >
                      <Share2 className="w-3 h-3" /> View &amp; Share <ExternalLink className="w-3 h-3" />
                    </Link>
                  </div>
                </div>
              </div>
            ))}
          </div>
        ) : (
          /* Fallback Sample Card Display if no user uploads exist yet */
          <div className="max-w-3xl mx-auto bg-[#F7F1DF] text-[#0A4C2B] border-2 border-[#0A4C2B] rounded-3xl p-8 text-center space-y-4 shadow-[8px_8px_0px_#0A4C2B]">
            <div className="w-16 h-16 rounded-full bg-[#FFD400] border-2 border-[#0A4C2B] flex items-center justify-center mx-auto shadow-[3px_3px_0px_#0A4C2B]">
              <Sparkles className="w-8 h-8 text-[#FF007A]" />
            </div>
            <h3 className="font-editorial-serif font-bold text-2xl uppercase text-[#0A4C2B]">
              Be the First Builder to Generate!
            </h3>
            <p className="text-sm text-[#0E6B3A]">
              Create your official Builder Pass or Profile Frame above to feature your identity on Supabase Storage.
            </p>
            <a
              href="#generator"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-[#FF007A] text-white font-editorial-display font-bold text-sm border-2 border-[#0A4C2B] shadow-[4px_4px_0px_#0A4C2B] hover:translate-x-0.5 transition-all uppercase"
            >
              Generate My Pass Now
            </a>
          </div>
        )}
      </div>
    </section>
  );
}
